[package]
name = "libjpeg-turbo"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "^0.2"
thiserror = "^1.0"

[build-dependencies]
anyhow = {version = "^1.0"}
bindgen = {version = "^0.57"}
cmake = {version = "^0.1"}

[features]
default = ["simd"]
simd = []